modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="GNU GPLv3" #mandatory

[[mods]]
modId="mteg"
version="1.0.1"
displayName="Mo' Than Enough Guns"
authors="MigaMi"
credits="Bomb787, MrCrayfish"
description="All the Mo' Guns weapons in the JEG Framework!"

[[dependencies.mteg]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mteg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mteg]]
    modId="jeg"
    mandatory=true
    versionRange="[0.3.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mteg]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"
